.formatter.exs
dev.exs

Allows omitting parens for consistency with other packages such as Phoenix Live Dashboard or Oban Web.
```elixir
error_tracker_dashboard "/errors"
error_tracker_dashboard("/errors")
```

Allow mounting the dashboard without parens

---

lib/error_tracker.ex
lib/error_tracker/schemas/error.ex
lib/error_tracker/schemas/stacktrace.ex
lib/error_tracker/web/live/show.html.heex

This change updates how some Erlang errors are handled and ensure they are stored and shown properly.
The root issue was that some Erlang errors are received as tuples and we need to convert them to Elixir exception the same way as Phoenix does on their Error pages, by calling `Exception.normalize`.
We also fixed storing and showing stractrace information on those cases in which no file is reported.
Closes #35

Fix some exceptions reporting

---

lib/error_tracker/repo.ex

In #31 we added a bug which caused exceptions when storing errors in PostgreSQL when using a custom prefix.
This change fixes the issue.

Fix prefix usage in PostgreSQL

---

dev.exs
guides/Getting Started.md
lib/error_tracker.ex
lib/error_tracker/repo.ex
lib/error_tracker/telemetry.ex

This change adds four telemetry events to allow third parties to attach to events regarding the life cycle of Events and Occurrences.
It currently emits events when:
- A new error is recorded
- An error is marked as resolved
- An error is marked as unresolved
- An occurrence is stored
Documentation has been updated.
Tests are not there yet because we are actively working in setting up the test suite in #34

Telemetry events

---

README.md
guides/Getting Started.md
lib/error_tracker/web/components/layouts/navbar.ex
lib/error_tracker/web/components/layouts/root.html.heex

Update the application to include the bug icon and the README to add some badges.

Add icon and update README

---

lib/error_tracker/migration/sql_migrator.ex

The `error_tracker_meta` table defines both `key` and `value` as `varchar(255)`. When inserting the `migration_timestamp` we were sending an integer, which was implicitly converted to a varchar in PostgreSQL but not in other PostgreSQL-compatible databases such as CockroachDB.
This change ensures that the `migration_timestamp` is sent to the DB with the right type and doesn't depend on implicit type conversions.
Fixes #43
---
To test this I set up a Cockroach DB [using Docker](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-linux.html#start-a-single-node-cluster) and then connected my local ErrorTracker instance to it. It failed right away when running the migrations.

Ensure migration_timestamp is a varchar

---

lib/error_tracker/web.ex

The dashboard inlines both the JS and CSS assets. Users with a Content Security Policy need to allow inline assets for the dashboard to work properly.
Closes #48

Document CSP settings for dashboard

---

lib/error_tracker/migration.ex
lib/error_tracker/migration/sql_migrator.ex
lib/error_tracker/repo.ex

This change adds `Repo.with_adapter/1` as suggested in https://github.com/elixir-error-tracker/error-tracker/pull/51#discussion_r1720918647

Use new function `Repo.with_adapter/1'

---

dev.exs
lib/error_tracker/web/components/layouts/root.html.heex
lib/error_tracker/web/hooks/set_assigns.ex
lib/error_tracker/web/router.ex

This pull request adds a new `:csp_nonce_assign_key` option to the `error_tracker_dashboard/2` macro. If provided, the error tracker will fetch the nonce from the given assign key and use it in the `<style>` and `<script>` tags.
This allows using the ErrorTracker dashboard in environments with a restricted content security policy without requiring the usage of `unsafe-inline`, which should be avoided.
This implementation is based on the [Phoenix LiveDashboard](https://hexdocs.pm/phoenix_live_dashboard/Phoenix.LiveDashboard.Router.html#live_dashboard/2) one.
I've updated the `dev.exs` script to use CSP headers. If we remove the new option we will see that the ErrorTracker dashboard doesn't have any styles.
Closes #58

Use CSP nonces for script and style tags

---

lib/error_tracker/migration/postgres/v01.ex
lib/error_tracker/migration/sqlite/v02.ex

The ErrorTracker tables use `id` as the primary key name. This was causing trouble when the client repository was configured to use a different column name for references since it tried to create a foreign key pointing to a non-existing column.
This commit explicitly states the referenced column name to avoid this problems.
To check this you can create a new Phoenix application that uses the error tracker and add the following configuration to the application repository:
```elixir
config :my_app, MyApp.Repo,
migration_primary_key: [name: :uuid, type: :binary_id],
migration_foreign_key: [column: :uuid, type: :binary_id]
```
Trying this on `main` will raise an error when running the migrations. The error is not present in this branch.
Closes #59

Use explicit column name for FK references

---

guides/Getting Started.md

As it may be seen in [Oban](https://hexdocs.pm/oban/installation.html) it is recommended to set up hard version on the initial migration, so we can ensure the ErrorTracker database matches the same schema over time.
This is important because other migrations may use our schema and if we do not specify it we may end up with the latest schema update (version 10 for example) when the next migration was expecting version 2.

Update install guides migration example

---

guides/Getting Started.md
lib/error_tracker.ex
lib/error_tracker/repo.ex

This change solves an issue in which an invalida content of the error context 
case the `Error` schema to be stored but not the `Occurrence`, which means that 
the error appears on the dashboard list but cannot be opened because the details 
were not stored.
On this change I change the store procedure to use a DB transaction and ensure 
that, if something fails, no data is stored and an exception is generated.
I thought about storing that exception ourselves but if the issue is not related 
to the data stored but other parts of the stack (network, DB, etc) it can end up 
in an infinite loop.
I have also updated the documentation so it states the requirements needed for 
the context data to be stored (basically, it has to be convertible to JSON).
Closes #65

Do not store error if context/occurrence is not valid

---

lib/error_tracker/integrations/oban.ex
lib/error_tracker/schemas/error.ex
lib/error_tracker/web/live/dashboard.html.heex
lib/error_tracker/web/live/show.ex
lib/error_tracker/web/live/show.html.heex

There was an error when an Oban worker returned an `{:error, reason}` tuple because Oban does not return an stacktrace (makes sense, as it is not an exception by itself).
Our code was not prepared for that use case. I modified it to handle it and circumvent the needed for source file and source function information.
After this change, empty stack traces and source information are not shown on the dashboard to avoid confusion.
As an extra feature I have also added the reporting of the `state` of the job (which is mostly ever `failure` for us).
The way to reproduce it is to have an Oban worker which returns a tuple `{:error, any()}` or just `:error`.
That use case generates an exception in the latest release and works as expected on this branch.
---
Closes #63

Fix reporting errors from Oban

---

lib/error_tracker/integrations/phoenix.ex

fixes https://github.com/elixir-error-tracker/error-tracker/issues/73

report errors that originate from LiveComponents

---

lib/error_tracker/integrations/phoenix.ex

As @odarriba and @numso discussed on #74 the current approach of adding LiveView event information to the process context may result in misleading information for certain errors.
> For example, if the following happened:
> 
> 1. mount the liveview
> 2. handle_event("something", params, socket) in the liveview
> 3. handle_info("something_else", socket) causing a re-render
> 4. render -> exception occurs
>
> I think live_view.event and live_view.event_params would still be in the error context when the exception was reported. They would have been assigned to context in step 2. But by step 4, that data could be irrelevant. Am I understanding that right?
This pull request adds the LiveView event information to the context only during exceptions and avoids the situations mentioned above. The …

Add LiveView event to context only during exceptions

---

guides/Getting Started.md
lib/error_tracker.ex
test/error_tracker_test.exs
test/support/case.ex

This change adds a new global flag named `:enabled` that allows to disable the error tracking on certain environments.
This behaviour can be done also with a custom ignorer using the changes that we will introduce in #79 , but I felt like this use case will be quite common in dev environments and having a fast way to just disable every error is useful.
Test have been added and documentation updated.
It is related to #81

Flag to globally disable error tracking

---

guides/Getting Started.md
lib/error_tracker/application.ex
lib/error_tracker/migration/postgres.ex
lib/error_tracker/migration/postgres/v03.ex
lib/error_tracker/migration/sqlite.ex
lib/error_tracker/migration/sqlite/v03.ex
lib/error_tracker/plugins/pruner.ex
lib/error_tracker/repo.ex
mix.exs
priv/repo/seeds.exs

This pull request adds a new `ErrorTracker.Plugins.Pruner` which automatically prunes resolved errors. This plugin can be used automatically or manually.
ℹ️ I've also added a new priv/repo/seeds.exs script that populates the db with some fake errors and occurrences. May be useful for testing the dashboard, pruning and other features easily.
Register the plugin under the ErrorTracker configuration. The pruner will run in the background every 30 minutes and remove up to 1000 resolved errors older than 5 minutes (this options can be overriden)
```elixir
config :error_tracker,
repo: MyApp.Repo,
otp_app: :my_app,
plugins: [ErrorTracker.Plugins.Pruner]
```
If you want to have more fine-grained control over when the pruner runs you can use the `ErrorTracker.Plugins.Pruner.prune_errors/1` …

Prune resolved errors

---

guides/Getting Started.md
lib/error_tracker.ex
lib/error_tracker/ignorer.ex
test/error_tracker/ignorer_test.exs

This pull request adds the new `ErrorTracker.Ignorer` behaviour that can be used by clients to ignore errors based on their attributes and context.
I've added a test to verify that it works as expected and also updated the docs and getting started guide.

Ignore Errors

---

lib/error_tracker/web/router.ex

Underscored functions are never imported by default. This should fix #90.
If you import the router on `main` you will see that the `parse_options` function is imported automatically:
```elixir
iex(1)> import ErrorTracker.Web.Router
ErrorTracker.Web.Router
iex(2)> h parse_options
No documentation for ErrorTracker.Web.Router.parse_options was found
```
If you do the same now you will se that the function is not imported and it tries to find it in the Kernel module.
```elixir
iex(1)> import ErrorTracker.Web.Router
ErrorTracker.Web.Router
iex(2)> h __parse_options__/2
No documentation for Kernel.__parse_options__/2 was found
```

Don't import private function name from router

---

lib/error_tracker.ex
lib/error_tracker/migration.ex
lib/error_tracker/schemas/error.ex
lib/error_tracker/schemas/occurrence.ex
lib/error_tracker/schemas/stacktrace.ex

This PR adds type specs to public functions as requested
Closes #84

Add typespecs for public functions

---

lib/error_tracker/plugins/pruner.ex

As far as i understand the code and the text below which also states the default of 24 hours, i think the 5 minutes are wrong.

fix docs for `Pruner` default max_age value

---

lib/error_tracker.ex
lib/error_tracker/filter.ex
test/error_tracker/filter_test.exs

Adds a `ErrorTracker.Filter` behavior that users can supply, it has a single function `sanitize/1` that takes an error context and returns a new error context which will be saved in the DB.
Closes #88

Add `ErrorTracker.Filter` behavior for modifying error context before saving

---

guides/Getting Started.md
lib/error_tracker.ex

Just a few additions to #94:
- We don't need to filter context when not tracking errors
- Mention how to filter context in the Getting Started guide

Filter context only when tracking errors

---

lib/error_tracker.ex

Explicitly allows string and atom keys. Fixes #101

Improve error context typespec

---

lib/error_tracker.ex
test/error_tracker_test.exs

Some frameworks such as Ash include breadcrumbs in their errors. This is provided by the fantastic Splode library ([details](https://bsky.app/profile/zachdaniel.dev/post/3l7qsyil4pg2c)).
This commit updates the ErrorTracker to detect such bread crumbs and include them in the occurrence context. In the future we may want to revisit this and store them in their own field separate from the context.
It is important to note that you don't have to use Ash or Splode to leverage this integration. Breadcrumbs will be automatically extracted from any exception that includes a `bread_crumbs` field.
I've discussed this with @zachdaniel and he kindly integrated the breadcrumbs on Ash main for create and change actions.
To test this you can clone the [Ash …

Store Ash bread crumbs in occurrence context

---

lib/error_tracker.ex
live.exs

For non-error tuples `Exception.normalize/3` returns the original payload, which may be anything. Some payloads such as tuples don't implement the `String.Chars` protocol. So calling `to_string/1` will fail. In such cases we fall back to `inspect/1`.
I made a few updates to the `live.exs` script to reproduce this problem. You can run `elixir live.exs` and click the button called «GenServer timeout». This will cause an error that should be recorded by the error tracker.
If you revert the changes that I made and try this same button you will se that the error payload cannot be converted to string and detaches the ErrorTracker telemetry handler.
Closes #109

Safely convert payloads to strings

---

lib/error_tracker/web/live/dashboard.html.heex
priv/static/app.css

The error list page was not pretty on mobile. This fixes the error list on mobile and closes #105
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

Improve dashboard for mobile devices

---

lib/error_tracker/web.ex
lib/error_tracker/web/router.ex

Improve docs regarding LiveView scope

---

.github/workflows/elixir.yml
.tool-versions

Updates the `.tool-versions` file to use Elixir 1.18 for dev and also updates the build matrix to test against Elixir 1.18 on the CI.

Support Elixir 1.18

---

lib/error_tracker/migration/postgres/v04.ex

The latest migration for PostgreSQL ignores the `prefix` option, causing the migration to fail when previous migrations were not using the `public` schema. This PR adds the `prefix` option to the `v04` migration.

Accept prefix option for PostgreSQL v04 migration

---

lib/error_tracker/migration/sql_migrator.ex

Thank you for this amazing library.
Quick fix for the following warning
```
warning: Range.new/2 and first..last default to a step of -1 when last < first. Use Range.new(first, last, -1) or first..last//-1, or pass 1 if that was your intention
```
This happens when rolling back the migrations (dev) or when removing `error_tracker` (prod)

Fix warning for negative range

---

.github/workflows/elixir.yml
lib/error_tracker/schemas/stacktrace.ex
test/error_tracker_test.exs

The errors are being grouped in a wrong way because a type mismatch comparison was done between the application name and the stacktrace application name.
The fix is to convert the configured application name to a string and be able to compare it with the stacktrace application name.
You can test it putting this script on the root project:
<details>
```elixir
Mix.install([
{:ecto_sql, "~> 3.0"},
{:postgrex, "~> 0.1"},
{:error_tracker, path: "."},
{:bandit, "~> 1.0"}
])
Application.put_env(:error_tracker, :repo, Repo)
Application.put_env(:error_tracker, :otp_app, :myapp)
Application.put_env(:error_tracker, :enabled, true)
defmodule AddErrorTracker do
use Ecto.Migration
def up, do: ErrorTracker.Migration.up(version: 4)
def down, do: ErrorTracker.Migration.down(version: 1)
end …
```

Fix error grouping issue

---

dev.exs
guides/Getting Started.md
lib/error_tracker.ex
lib/error_tracker/ignorer.ex
lib/error_tracker/migration/mysql.ex
lib/error_tracker/migration/mysql/v05.ex
lib/error_tracker/migration/postgres.ex
lib/error_tracker/migration/postgres/v05.ex
lib/error_tracker/migration/sqlite.ex
lib/error_tracker/migration/sqlite/v05.ex
lib/error_tracker/schemas/error.ex
lib/error_tracker/telemetry.ex
lib/error_tracker/web/components/core_components.ex
lib/error_tracker/web/live/dashboard.ex
lib/error_tracker/web/live/dashboard.html.heex
lib/error_tracker/web/live/show.ex
lib/error_tracker/web/live/show.html.heex
priv/static/app.css
test/error_tracker/telemetry_test.exs

This pull request adds a new `muted` field to errors. Noisy errors can be muted in the UI so integrations and notifications can ignore them as well.
In the end I decided to use the _mute_ instead of _silence_ as I think that _mute_ and _unmute_ are fairly commonly understood terms.
This is an addition to the capability of ignoring errors that we already have, and enables the possibility of tracking error occurrences but don't notify them. Closes #117
New mute action in the error detail page:
Mute and unmute actions in the dashboard page

Mute error occurrences

---

lib/error_tracker/web/components/core_components.ex
lib/error_tracker/web/live/dashboard.ex
lib/error_tracker/web/live/dashboard.html.heex
lib/error_tracker/web/live/show.ex
lib/error_tracker/web/live/show.html.heex
lib/error_tracker/web/router/routes.ex
lib/error_tracker/web/search.ex
priv/static/app.css

This pull request contains three improvements to the web dashboard navigation:
- Current filters are persisted when navigating between the error list and detail pages
Closes #136 
- In the error detail page there are new navigation links to the prev and next occurrence
Closes #139 
- Navigating back to the dashboard page now happens over the existing websocket connection instead of doing a full page reload
To test this:
1. Open the dev script with `iex dev.exs`
2. Generate a few errors if you don't have any yet
3. Open the web dashboard and apply some filters
4. Navigate to an error detail page
5. Navigate between error occurrences using the new links and the selector (notice the screenshot below)
6. Navigate back to the dashboard
7. Confirm that the filters are still applied

Improve web dashboard navigation

---

guides/Getting Started.md
lib/error_tracker/schemas/error.ex

This addresses #153.
We thought about it and came to the conclusion that it would be good to change the type declaration for the module. Open for discussion, because that could potentially be a breaking change of the library if users previously had implementations of `ErrorTracker.Ignorer` that matched on non-string types (although, arguably those implementations would never have worked).

Improve documentation of ErrorTracker.Error kind field
